### ISSUE TITLE
Tutor open lab signup form

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/open-lab-scheduler#10]
As a logged in user, if my email appears in the tutor assignment table, I can get a list of links of all my tutor assignments, and click on any one of them, and get taken to a page with 30 minutes slots for all of the available times and rooms for that quarter.

That allows me to create records in the TimeSlotAssignment table.

id, slot id, tutor assigment id, start time

acceptance criteria
- [ ] you can view all the time slots to sign up for 
- [ ] be able to sign up for an 
available time slot
- [ ] option to edit availability 
- [ ] remove availability from a time slot.

**Comment by jseong1100** [comment]
A html file should be created that is configured to display all of a tutor's assignments for a quarter, and is also able to display all of the available times and rooms for a quarter.
