### ISSUE TITLE
Add an admin table, plus Create/Delete operations for Admin (that gives the students a model to follow)

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/open-lab-scheduler#15]
Initial admin email should be defined in application.properties

If you are logged in as an admin, there should be an navigation item called Users, with a menu dropdown that currently has only Admins  in it. (later it will also have Users).   

You add admins by putting in their @ucsb.edu email address.    The table just has add, delete. 

When a user logs in, we check whether or not their email is in the admin table.

**Comment by scottpchow23** [comment]
Addressed by #19.
