### ISSUE TITLE
Add Google OAuth 

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/open-lab-scheduler#16]
Also add the Bootstrap nav and footer, and the login/logout link.

And, we added roles for:
* a single admin defined in application.properites
* member which is anyone that has the app defined hosted_domain (@ucsb.edu)
* guest everyone else has a google oauth of any kind.

Later work might restrict logins to only @ucsb.edu emails that are in the admin or tutor table.

Or perhaps even just any google email that's in those tables.

**Comment by scottpchow23** [comment]
Addressed by #20 and #19.
