### ISSUE TITLE
Refactor course offering table to use foreign key to instructors table

### ISSUE THREAD

**Issue by qiandrew** [ucsb-cs56-w20/open-lab-scheduler#37]
NOTE: The CRUD ops for the courseOffering table need to be finished BEFORE this can be started. If that is not done in time, this story may not be done this quarter.

**Comment by li-el** [comment]
In the database where the tables are stored add a column to the course table with a key to a professor from the instructors table to ensure that all courses displayed as offered are in fact linked to some instructor.
