### ISSUE TITLE
As an instructor, if my email is in the Instructor table, I see a "My Courses" page when I am logged in

### ISSUE THREAD

**Issue by qiandrew** [ucsb-cs56-w20/open-lab-scheduler#38]
- [x] There exists an html file for the "My Courses" page

- [x] There exists a controller that routes to the "My Courses" page that checks to make sure the user's email is in the instructor table

- [x] The nav bar button for the page should only show up if the user is logged in and if the user's email is in the Instructor table

**Comment by shiran8338** [comment]
In the login.html, it is possible to write a section of code so that if the user is an instructor and successfully login, he or she can be redirect to the page of "My Courses."

**Comment by mpakinggan** [comment]
https://github.com/ucsb-cs56-w20/open-lab-scheduler/tree/t-6pm-c-myCoursesPage
