### ISSUE TITLE
On the "My Courses" page, the list of courses is given as a list of links that I can click on to see the tutors assigned to that course

### ISSUE THREAD

**Issue by qiandrew** [ucsb-cs56-w20/open-lab-scheduler#39]
- [x] The MyCourses page for instructors is available only to instructors with emails in the courseOffering table
- [x] When logged in as instructor smith@ucsb.edu, only courses from the courseOffering table that have smith@ucsb.edu are shown on the menu
- [x] Each of those courses is a link to see the tutors assigned to that courses.  NOTE THAT THIS COULD BE FACTORED INTO A SEPARATE ISSUE.

**Comment by mpakinggan** [comment]
Would have to edit the html page to change the individual course names into links to the list of tutors for that course. Edit might look like: 
`<td><a th:href="${link to tutors}" th:text="${course name}"></a></td>`
