### ISSUE TITLE
On the "My Courses" page, I see a list of all the courses for which I am the instructor (my email is associated with the course offering)

### ISSUE THREAD

**Issue by qiandrew** [ucsb-cs56-w20/open-lab-scheduler#40]
- [x]  When logged in as an instructor, I can see a MyCourses page (should be done in previous story)

- [x] On the MyCourses page there should be a table associated with all the courses that an instructor is an instructor for

**Comment by gbaroni888** [comment]
On whatever hmtl the "My Courses" page is on, I'd add a table that loops through and displays all the courses associated with the email. If the data is stored in a JSON, I'd need to add a method that converts the JSON into a java object.

**Comment by sssaaaaaarrra** [comment]
t-6pm-c-displayInstructorCourses

**Comment by sssaaaaaarrra** [comment]
As an instructor, I can view all the courses that I am an instructor for (which are associated with my email), so that I can more easily visualize all the classes that I am an instructor for and so that all my courses are in one place.

**Comment by sssaaaaaarrra** [comment]
- [ ] When logged in as an instructor, I can see a MyCourses page (should be done in previous story)

- [ ]  On the MyCourses page there should be a table associated with all the courses that an instructor is an instructor for
