### ISSUE TITLE
As an Instructor, I can delete a course so that I can remove unneeded courses

### ISSUE THREAD

**Issue by friedcelery** [ucsb-cs56-w20/open-lab-scheduler#61]
As an Admin,
I can delete a course offering,
So that it can be removed from the course offering list.

Acceptance criteria:
__specific course offering removed from course offering repository
__course offering no longer shows up on table of all course offerings

**Comment by JamesSchwellenbach** [comment]
in src/main/resources/templates/admin/form.html, we need to add functionality for admin to be able to delete courses on the course list, will need to make sure that this option is only added for admin users.
