### ISSUE TITLE
As a tutor, I can log and get a "tutor view" so that I can navigate to "my schedule" or "open lab signup" tabs

### ISSUE THREAD

**Issue by yinonrousso** [ucsb-cs56-w20/open-lab-scheduler#74]
This would require checking the tutor table to see if a given user's email exists. If it does, they would get the tutor view. 

Note: Tutors do NOT also have the "admin view"

**Comment by AaronHuanger** [comment]
w-7pm-c-tutorRole

**Comment by AaronHuanger** [comment]
https://github.com/ucsb-cs56-w20/open-lab-scheduler/pull/77
