### ISSUE TITLE
Public facing schedule select qtr/course, show the list of all times slots that have >= tutor, and which tutors are in that slot.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/open-lab-scheduler#9]
This page should be the new home page, and will NOT require a login.

When this becomes the home page, we need an index page room availability that is only shown to admins.

Public facing schedule select qtr/course, show the list of all times slots that have >= tutor, and which tutors are in that slot.

**Comment by Shellyfc** [comment]
We will need a data structure to store time slots and available tutors and then use an HTML file to layout info maybe in a table. Different permission levels may be given to users with different google login emails.
